// flow-typed signature: f2c9719f9508289e4ff9be2b30ee11bc
// flow-typed version: <<STUB>>/postcss-cli_v^6.1.3/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-cli/lib/args' {
  declare module.exports: any;
}

declare module 'postcss-cli/lib/depGraph' {
  declare module.exports: any;
}

declare module 'postcss-cli/lib/getMapfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-cli/index' {
  declare module.exports: $Exports<'postcss-cli'>;
}
declare module 'postcss-cli/index.js' {
  declare module.exports: $Exports<'postcss-cli'>;
}
declare module 'postcss-cli/lib/args.js' {
  declare module.exports: $Exports<'postcss-cli/lib/args'>;
}
declare module 'postcss-cli/lib/depGraph.js' {
  declare module.exports: $Exports<'postcss-cli/lib/depGraph'>;
}
declare module 'postcss-cli/lib/getMapfile.js' {
  declare module.exports: $Exports<'postcss-cli/lib/getMapfile'>;
}
